# Generated by Django 4.0.3 on 2022-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО завуча')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='фото завуча')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Зауч',
                'verbose_name_plural': 'Заучи',
            },
        ),
    ]
